create table public.ingestion_checkpoints (
  id bigint generated by default as identity primary key,
  provider text not null,
  dataset text not null,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  last_successful_trade_date date,
  last_successful_fetch_at timestamptz,
  last_run_status text not null,
  error_message text,
  updated_at timestamptz not null default now(),
  constraint ingestion_checkpoints_identity_key unique (provider, dataset, stock_id),
  constraint ingestion_checkpoints_provider_not_blank check (length(btrim(provider)) > 0),
  constraint ingestion_checkpoints_dataset_not_blank check (length(btrim(dataset)) > 0),
  constraint ingestion_checkpoints_status_check
    check (last_run_status in ('pending', 'running', 'succeeded', 'failed'))
);

create index ingestion_checkpoints_stock_id_idx
  on public.ingestion_checkpoints (stock_id);

alter table public.ingestion_checkpoints enable row level security;

revoke all on table public.ingestion_checkpoints from anon, authenticated;
revoke all on sequence public.ingestion_checkpoints_id_seq from anon, authenticated;
