create table public.stocks (
  id bigint generated by default as identity primary key,
  ticker text not null,
  company_name text not null,
  sector text,
  subsector text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stocks_ticker_key unique (ticker),
  constraint stocks_ticker_format check (ticker ~ '^[A-Z0-9]{1,12}$'),
  constraint stocks_company_name_not_blank check (length(btrim(company_name)) > 0)
);

create table public.daily_market_data (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  trade_date date not null,
  open numeric(18, 4) not null,
  high numeric(18, 4) not null,
  low numeric(18, 4) not null,
  close numeric(18, 4) not null,
  previous numeric(18, 4) not null,
  volume_shares bigint not null,
  value_idr numeric(24, 2) not null,
  frequency bigint not null,
  foreign_buy_shares bigint,
  foreign_sell_shares bigint,
  non_regular_volume_shares bigint,
  non_regular_value_idr numeric(24, 2),
  non_regular_frequency bigint,
  source text not null,
  ingested_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_market_data_stock_date_key unique (stock_id, trade_date),
  constraint daily_market_data_prices_positive check (
    open > 0 and high > 0 and low > 0 and close > 0 and previous > 0
  ),
  constraint daily_market_data_ohlc_valid check (
    high >= greatest(open, close, low) and low <= least(open, close, high)
  ),
  constraint daily_market_data_volume_nonnegative check (volume_shares >= 0),
  constraint daily_market_data_value_nonnegative check (value_idr >= 0),
  constraint daily_market_data_frequency_nonnegative check (frequency >= 0),
  constraint daily_market_data_foreign_buy_nonnegative check (foreign_buy_shares is null or foreign_buy_shares >= 0),
  constraint daily_market_data_foreign_sell_nonnegative check (foreign_sell_shares is null or foreign_sell_shares >= 0),
  constraint daily_market_data_non_regular_volume_nonnegative check (non_regular_volume_shares is null or non_regular_volume_shares >= 0),
  constraint daily_market_data_non_regular_value_nonnegative check (non_regular_value_idr is null or non_regular_value_idr >= 0),
  constraint daily_market_data_non_regular_frequency_nonnegative check (non_regular_frequency is null or non_regular_frequency >= 0),
  constraint daily_market_data_source_not_blank check (length(btrim(source)) > 0)
);

create table public.ingestion_runs (
  id bigint generated by default as identity primary key,
  provider text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null,
  requested_date date,
  rows_received integer not null default 0,
  rows_inserted integer not null default 0,
  rows_updated integer not null default 0,
  error_message text,
  constraint ingestion_runs_provider_not_blank check (length(btrim(provider)) > 0),
  constraint ingestion_runs_status_valid check (status in ('running', 'succeeded', 'failed')),
  constraint ingestion_runs_counts_nonnegative check (
    rows_received >= 0 and rows_inserted >= 0 and rows_updated >= 0
  ),
  constraint ingestion_runs_finished_after_started check (
    finished_at is null or finished_at >= started_at
  )
);

create index daily_market_data_stock_date_desc_idx
  on public.daily_market_data (stock_id, trade_date desc);

create index ingestion_runs_started_at_desc_idx
  on public.ingestion_runs (started_at desc);

alter table public.stocks enable row level security;
alter table public.daily_market_data enable row level security;
alter table public.ingestion_runs enable row level security;

revoke all on table public.stocks from anon, authenticated;
revoke all on table public.daily_market_data from anon, authenticated;
revoke all on table public.ingestion_runs from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

comment on column public.daily_market_data.volume_shares is
  'Source-of-truth market volume in shares. Derive lots by dividing by 100.';
comment on column public.daily_market_data.frequency is
  'Source transaction frequency. Frequency Analyzer returns null when this is zero.';
